export const GET_DATA_LOADING = "GET_DATA_LOADING";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";

export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY"; 
export const FILTER_BY_QUERY = "FILTER_BY_QUERY";

export const REMEMBERED_TAG = "REMEMBERED_TAG";